// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWLn1iUIV-fcoNRhydxrJ9r3XEjo-R448',
    appId: '1:232859657045:web:858d91b47f40dc3b7245dc',
    messagingSenderId: '232859657045',
    projectId: 'flutterpushnoti-e1e73',
    authDomain: 'flutterpushnoti-e1e73.firebaseapp.com',
    storageBucket: 'flutterpushnoti-e1e73.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHZYvpkZuSIxGGy_jMpUJLWMCXCnpTL6Q',
    appId: '1:232859657045:android:8b1aae371917477f7245dc',
    messagingSenderId: '232859657045',
    projectId: 'flutterpushnoti-e1e73',
    storageBucket: 'flutterpushnoti-e1e73.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-VjIF24SLP-EbUgmgk5EQdEO-uLaaGgc',
    appId: '1:232859657045:ios:a1c44a92d074e9717245dc',
    messagingSenderId: '232859657045',
    projectId: 'flutterpushnoti-e1e73',
    storageBucket: 'flutterpushnoti-e1e73.appspot.com',
    iosBundleId: 'com.example.flutterNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-VjIF24SLP-EbUgmgk5EQdEO-uLaaGgc',
    appId: '1:232859657045:ios:1f7614f0e3aa1d037245dc',
    messagingSenderId: '232859657045',
    projectId: 'flutterpushnoti-e1e73',
    storageBucket: 'flutterpushnoti-e1e73.appspot.com',
    iosBundleId: 'com.example.flutterNotification.RunnerTests',
  );
}
